#!/usr/bin/env python2
# -*- coding=utf-8 -*-
# if you have any suggestions, you can email me at oooo4dzd@gmail.com
#great thanks to kuwo music

import os, gtk, pynotify,webkit,gobject,sys,webbrowser

URL = "http://topic.kugou.com/radio/"
ICON = os.path.join(os.path.dirname(__file__), 'pics/kugou.png')# change it to ur own favoured ico
icon=os.path.join(os.path.dirname(__file__), 'pics/note_2.png')
VERSION = "Gnome3"
NAME = "酷狗电台"
def autoscroll_view(view, allocation):
	parent = view.get_parent()
	adj = parent.get_vadjustment()
	adj.value = 80
	parent.set_vadjustment(adj)
	adj = parent.get_hadjustment()
	adj.value = 115
	parent.set_hadjustment(adj)
	parent.set_policy(gtk.POLICY_NEVER,gtk.POLICY_NEVER)

class WebBrowser(gtk.Window):	
	
	def __init__(self):	
		gtk.Window.__init__(self)
		self.set_default_size( 545,370)
		
		scrolled_window = gtk.ScrolledWindow(hadjustment=None, vadjustment=None)
		
		self.page = webkit.WebView()
		scrolled_window.add(self.page)
		self.add(scrolled_window)
		self.show_all()
		self.page.open(URL)
		self.connect("delete_event", self.minimize)
		self.connect('check-resize', self.check_resize)
		self.page.connect('size-allocate', autoscroll_view)
		
	def minimize(self, widget, event, data=None):
		self.hide()
		return True
	def check_resize(self, window):
		self.set_size_request(545,370)
	

	

class Tray():
	
	def __init__(self, window):
		self.window = window	
		self.window.set_title(NAME)		
		self.tray = gtk.StatusIcon()
		self.tray.set_from_file(ICON)
		self.window.set_icon_from_file(icon)
		self.tray.set_tooltip(NAME + '\n ' + VERSION)
		self.tray.connect('activate', self.clickTray)
		self.tray.connect('popup-menu', self.quit)
		
	
	def clickTray(self, widget):
		if self.window.get_property('is-active'):
			self.window.hide()
		else:
			self.window.present()

	
	def quit(self,widget,event, data=None):
		gtk.main_quit()
		
	
		
	


class music():
	
	def __init__(self):
		self.window = WebBrowser()
		self.tray = Tray(self.window)

if __name__ == '__main__':
	music()
	gtk.main()
